(ns pad.protocols.procs|)

(defprotocol Procs|
  (-op-start [_])
  (-op-stop [_])
  (-op-restart [_])
  (-op-started [_])
  (-op-stopped [_])
  (-op-error [_])
  (-op-up [_])
  (-op-down [_])
  (-op-downup [_])
  (-start [_ proc-id out|])
  (-stop [_ proc-id out|])
  (-started [_ proc-id])
  (-stopped [_ proc-id])
  (-error [_ id err])
  (-restart [_ proc-id out|])
  (-up [_ procs ctx out|])
  (-down [_ procs ctx out|]))