#!/bin/bash

dev(){
  docker-compose --compatibility \
  -f dc-dev.yml \
  "$@"
}

up(){
  dev up -d --build "$@"
}

down(){
  dev down "$@"
}

build(){
  # https://docs.docker.com/compose/reference/build/
  $1 build $2 "${@:3}"
}

run(){
  # https://docs.docker.com/compose/reference/run/
  $1 run --service-ports $2 "${@:3}"
}

runbash(){
  # https://docs.docker.com/compose/reference/run/
  run $1 $2 bash -c "bash;"
}

buildrun(){
  build $1 $2
  run $1 $2 "${@:3}"
}

mount(){
  build $1 $2 "${@:3}"
  runbash $1 $2
}

into(){
  $1 exec $2 bash -c "bash;"
}

base(){
  docker-compose --compatibility \
  -f dc-base.yml \
  build \
  "$@"
}

prod(){
  docker-compose --compatibility \
  -f dc-prod.yml \
  "$@"
}

release(){
  base
  prod build
}

dgraph(){
  docker-compose --compatibility \
  -f dc-dgraph.yml \
  "$@"
}

traefik(){
  docker-compose --compatibility \
  -f dc-traefik.yml \
  "$@"
}

dock(){
  docker-compose --compatibility \
  -f dc-dock.yml \
  "$@"
}


scale(){
  dc up -d --build --scale whoami=2
}

behold_loadbalance(){
  curl -H Host:whoami.docker.localhost http://127.0.0.1
}

permissions(){
  sudo chmod -R 777 volumes
}

symlinks(){
  ln -s ../../../src containers/src
}


"$@"