version: "3.7"

networks:
  compute.server:
    name: compute.server

services:

  app:
    image: starnet.app
    volumes:
      - ./app:/opt/app
    build:
      context: ./app
      dockerfile: ./Dockerfile
    ports:
      - 7788:7788
      - 8080:8080
    # command: bash f dev
    command: tail -f /dev/null
    environment:
      - BUILD=dev
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4096M

  ui:
    image: starnet.ui
    volumes:
      - ./ui:/opt/app
    build:
      context: ./ui
      dockerfile: ./Dockerfile
    ports:
      - 8899:8899
      - 9500:9500
      - 9630:9630
    # command: bash f main
    command: tail -f /dev/null
    environment:
      - BUILD=dev
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4096M