#!/bin/bash

shadow(){
    ./node_modules/.bin/shadow-cljs "$@"
}

dev(){
  npm i
  shadow -A:shadow:core:ui:p2p watch :ui :p2p
}

server(){
    shadow -A:shadow:core:ui:p2p server
    # yarn server
}

compile(){
    npm i
    shadow -A:shadow:core:ui:p2p compile :ui :p2p
}

release(){
    npm i
    shadow -A:shadow:core:ui:p2p release :ui :p2p
}


"$@"