#!/bin/bash


compile(){
  mkdir -p classes
  rm -rf classes/*
  clojure -A:core:dev:local -m starnet.alpha.aux.compile
}

test(){
  clojure -A:core:dev:local -m starnet.alpha.tests
}

dev(){
  compile
  clj -A:core:dev:local -m starnet.alpha.main
}

permissions(){
    sudo chmod -R 777 tmp/ 
}

dock() {
  
    docker build -t starnet.app -f Dockerfile ../../
    docker run  --rm \
                --cpus=4.0 \
                --memory=8g \
                --name starnet.app \
                -it \
                --network starnet \
                -p 7788:7788 \
                -p 8080:8080 \
                -p 8443:8443 \
                -v "$(cd ../../ && pwd)"/system:/ctx/system \
                -v "$(cd ../../ && pwd)"/apps/server:/ctx/app \
                --mount type=volume,source=starnet.crux,target=/ctx/data,volume-nocopy=true \
                -e "appenv={:optimized false}" \
                 starnet.app \
                 bash
}

keystore(){
  keytool -keystore resources/keystore.jks -alias keystore -keyalg RSA -keysize 2048 -sigalg SHA256withRSA -genkey -validity 36500
}

gen_ec(){
  # https://funcool.github.io/buddy-sign/latest/#generate-keypairs
  openssl ecparam -name prime256v1 -out resources/ecparams.pem
  openssl ecparam -in resources/ecparams.pem -genkey -noout -out resources/ecprivkey.pem
  openssl ec -in resources/ecprivkey.pem -pubout -out resources/ecpubkey.pem
  chmod -R 777 resources

}

gen_rsa(){
  # https://funcool.github.io/buddy-sign/latest/#generate-keypairs
  RANDOMSTRING=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
  OUTPUT=resources/passphrase.tmp
  rm $OUTPUT
  printf $RANDOMSTRING >> $OUTPUT
  PASSOUT=file:resources/passphrase.tmp
  openssl genrsa -aes256 -passout $PASSOUT -out resources/privkey.pem 2048
  openssl rsa -pubout -passin $PASSOUT  -in resources/privkey.pem -out resources/pubkey.pem
  chmod -R 777 resources

}

"$@"