#!/bin/bash

dc(){
  docker-compose --compatibility \
  -f dc-dev.yml \
  "$@"
}

up(){
  dc up -d --build "$@"
}

down(){
  dc down "$@"
}

run(){
  # https://docs.docker.com/compose/reference/run/
  dc run $1 bash -c "bash;"
}

term(){
  dc exec $1 bash -c "bash;"
}

base(){
  docker-compose --compatibility \
  -f dc-base.yml \
  build \
  "$@"
}

prod(){
  docker-compose --compatibility \
  -f dc-prod.yml \
  "$@"
}

release(){
  base
  prod build
}

dgraph(){
  docker-compose --compatibility \
  -f dc-dgraph.yml \
  "$@"
}

traefik(){
  docker-compose --compatibility \
  -f dc-traefik.yml \
  "$@"
}


scale(){
  dc up -d --build --scale whoami=2
}

behold_loadbalance(){
  curl -H Host:whoami.docker.localhost http://127.0.0.1
}

permissions(){
  sudo chmod -R 777 volumes
}

symlinks(){
  ln -s ../../../src containers/src
}


"$@"