#!/bin/bash


compile(){
  mkdir -p classes
  rm -rf classes/*
  clojure -A:core:dev -m starnet.app.alpha.compile
}

test(){
  clojure -A:core:dev:local -m starnet.app.alpha.tests
}

dev(){
  compile
  clj -A:core:dev:local -m starnet.app.alpha.main
}

permissions(){
    sudo chmod -R 777 tmp/ 
}

dock() {
  
    docker build -t starnet.app -f Dockerfile ..
    docker run  --rm \
                --name starnet.app \
                -it \
                --network starnet \
                -p 7788:7788 \
                -p 8080:8080 \
                -v "$(cd ../ && pwd)":/ctx \
                --mount type=volume,source=starnet.crux,target=/ctx/data,volume-nocopy=true \
                -e "appenv={:optimized false}" \
                 starnet.app \
                 bash
}


"$@"