#!/bin/bash

clean(){
    rm -rf resources/out out
}

purge(){
    clean
    rm -rf  .shadow-cljs .cpcache 
}

shadow(){
    ./node_modules/.bin/shadow-cljs "$@"
}

server(){
    shadow -A:core:dev server
    # yarn server
}

dev(){
    npm i
    shadow -A:core:dev watch :extension :bootstrap :tabapp 
    # shadow -A:core:dev watch :extension :bootstrap 
}

tree(){
    clojure -A:core:dev:optimized -Stree
}

compile(){
    npm i
    shadow -A:core:dev compile :extension :bootstrap :tabapp
}

dock() {

    docker build -t mult -f Dockerfile .
    docker run  --rm \
                --cpus=4.0 \
                --memory=4g \
                --name mult \
                -it \
                -p 5100:5100 \
                -p 5101:5101 \
                -p 5102:5102 \
                -v "$(pwd)":/ctx/app \
                -v "$(cd ../../ && pwd)":/ctx/code \
                 mult \
                 bash
}


cljs_compile(){
    clj -A:core:dev -m cljs.main -co build.edn -c mult.extension
}

fwm(){
    clojure -A:core:dev \
    -m nrepl.cmdline  \
    --middleware "[cider.nrepl/cider-middleware cider.piggieback/wrap-cljs-repl]" \
    --bind "0.0.0.0" --port 5100
}

"$@"