#!/bin/bash


dc(){
  docker-compose --compatibility \
  -f docker-compose.yml \
  "$@"
}

up(){
  dc up -d --build
}

down(){
  dc down
}

term(){
  dc exec $1 bash -c "bash;"
}

remove_volumes(){
  docker volume rm starnet.kafka
}

permissions(){
  sudo chmod -R 777 volumes
}


"$@"