#!/bin/bash

dev(){
    npm i
    shadow -A:core watch app
    # npx shadow-cljs -A:dev:local watch app
    # yarn dev
}

clean(){
    rm -rf .shadow-cljs node_modules .cpcache resources/public/js-out
}

shadow(){
    ./node_modules/.bin/shadow-cljs "$@"
}

prod(){
    npm i
    shadow -A:core:prod release app
}

server(){
    shadow -A:core server
    # yarn server
}

dock() {
    docker build -t starnet.ui .
    docker run  --rm \
                --name starnet.ui \
                -it \
                -p 8899:8899 \
                -p 9500:9500 \
                -p 9630:9630 \
                -v "$(pwd)":/app/root \
                 starnet.ui \
                 bash
}

"$@"